version: "3.8"

services:
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200" # Development server
      - "9876:9876" # Karma test runner
    environment:
      - NODE_ENV=development
    command: ng serve --host 0.0.0.0 --port 4200 --poll 2000 --disable-host-check
